---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      # We only include apt because of an issue installing java where ubuntu
      # requires an apt-get update in order to successfully run
      - recipe[apt]
      - recipe[serf]
    attributes:
      serf:
        agent:
          # Have to provide a real config value otherwise serf won't start
          log_level: info
        init_info:
          fake: value
